default_language_version:
  python: python3.14
ci:
  skip: [mypy]  # venv is too big; runs with gihub action instead

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-docstring-first
  - id: debug-statements
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: [--autofix]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.16.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix, --trailing-commas]
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v3.2.0
  hooks:
  - id: setup-cfg-fmt
    args: [--min-py-version, '3.14']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.12
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.20.2
  hooks:
  - id: mypy
    additional_dependencies: [aiosqlite>=0.21.0, homeassistant-stubs, manager-for-ynab>=1.6.3, sqlite-export-for-ynab>=2.7.0]
