[tox]
envlist = py314,pre-commit

[testenv]
deps = -rrequirements-dev.txt
commands_pre =
    python -c "import json, pathlib, subprocess, sys; manifest = json.loads(pathlib.Path('custom_components/ha_manager_for_ynab/manifest.json').read_text()); subprocess.check_call([sys.executable, '-m', 'pip', 'install', *manifest['requirements']])"
commands =
    coverage erase
    coverage run -m pytest {posargs:tests}
    coverage report

[testenv:pre-commit]
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure
