pending_income:
  fields:
    for_real:
      required: true
      example: false
      default: false
      selector:
        boolean:
    sync:
      required: true
      example: true
      default: true
      selector:
        boolean:
    quiet:
      required: true
      example: false
      default: false
      selector:
        boolean:

auto_approve:
  fields:
    for_real:
      required: true
      example: false
      default: false
      selector:
        boolean:
    sync:
      required: true
      example: true
      default: true
      selector:
        boolean:
    quiet:
      required: true
      example: false
      default: false
      selector:
        boolean:

sqlite_export:
  fields:
    full_refresh:
      required: true
      example: false
      default: false
      selector:
        boolean:
    quiet:
      required: true
      example: false
      default: false
      selector:
        boolean:

sqlite_query:
  fields:
    sync:
      required: true
      example: true
      default: true
      selector:
        boolean:
    sql:
      required: true
      example: SELECT * FROM budgets LIMIT 10
      selector:
        text:
          multiline: true
