name: release

on:
  push:
    tags:
    - '**'

permissions: {}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: mxr/workflows/.github/workflows/github-release.yml@4f57658477fc69ee1912c6f1d9f43c807bee852a # v0.1.3
    permissions:
      contents: write
