name: release

on:
  push:
    tags:
    - '**'

permissions: {}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: mxr/workflows/.github/workflows/github-release.yml@a762c9558b6ece45521c72b5c91c73fad62bd3e6 # v0.1.4
    permissions:
      contents: write
